spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
logging:
  level:
    com.com,qks.mapper: debug
